param(
  [string]$Profile = "standard",
  [string]$DistributionManifestPath = "",
  [string]$CentralEnvPath = "",
  [switch]$DryRun,
  [switch]$Force,
  [switch]$NoCreateCentralEnv
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$RepoRoot = Split-Path -Parent $PSScriptRoot

function Resolve-RepoPath {
  param([Parameter(Mandatory = $true)][string]$Path)
  if ([System.IO.Path]::IsPathRooted($Path)) {
    return $Path
  }
  return Join-Path $RepoRoot ($Path -replace "/", [System.IO.Path]::DirectorySeparatorChar)
}

function Read-JsonFile {
  param([Parameter(Mandatory = $true)][string]$Path)
  return Get-Content -Raw -LiteralPath (Resolve-RepoPath $Path) | ConvertFrom-Json
}

function Get-OptionalProperty {
  param(
    [Parameter(Mandatory = $true)]$Object,
    [Parameter(Mandatory = $true)][string]$Name,
    [object]$Default = $null
  )
  $property = $Object.PSObject.Properties[$Name]
  if ($null -eq $property -or $null -eq $property.Value) {
    return $Default
  }
  return $property.Value
}

function Read-DotEnvMap {
  param([Parameter(Mandatory = $true)][string]$Path)
  $map = @{}
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
    return $map
  }
  foreach ($line in Get-Content -LiteralPath $Path) {
    if ($line -match '^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
      $map[$Matches[1]] = $Matches[2]
    }
  }
  return $map
}

function Convert-DotEnvTemplate {
  param(
    [Parameter(Mandatory = $true)][string]$TemplatePath,
    [Parameter(Mandatory = $true)]$Values,
    [Parameter(Mandatory = $true)][string]$CentralPath
  )
  $lines = @(
    "# Generated by scripts/render-env-files.ps1 from $CentralPath",
    "# Edit the central env, then rerun the renderer. Do not commit this file.",
    ""
  )
  foreach ($line in Get-Content -LiteralPath $TemplatePath) {
    if ($line -match '^(\s*(?:export\s+)?)([A-Za-z_][A-Za-z0-9_]*)(\s*=\s*)(.*)$') {
      $prefix = $Matches[1]
      $key = $Matches[2]
      $separator = $Matches[3]
      if ($Values.ContainsKey($key)) {
        $lines += "$prefix$key$separator$($Values[$key])"
        continue
      }
    }
    $lines += $line
  }
  return $lines
}

function Copy-IfMissing {
  param(
    [Parameter(Mandatory = $true)][string]$Source,
    [Parameter(Mandatory = $true)][string]$Target,
    [string]$Label = "file"
  )
  if (-not (Test-Path -LiteralPath $Source -PathType Leaf)) {
    if ($DryRun) {
      Write-Warning "$Label template not present yet: $Source"
      Write-Host "New-Item -ItemType Directory -Force -Path $(Split-Path -Parent $Target)"
      Write-Host "Copy-Item $Source $Target"
      return
    }
    throw "$Label template missing: $Source"
  }
  if ((Test-Path -LiteralPath $Target) -and -not $Force) {
    Write-Host "exists: $Target"
    return
  }
  $parent = Split-Path -Parent $Target
  if ($DryRun) {
    Write-Host "New-Item -ItemType Directory -Force -Path $parent"
    Write-Host "Copy-Item $Source $Target"
    return
  }
  New-Item -ItemType Directory -Force -Path $parent | Out-Null
  Copy-Item -LiteralPath $Source -Destination $Target -Force:$Force
  Write-Host "created: $Target"
}

if ([string]::IsNullOrWhiteSpace($DistributionManifestPath)) {
  $DistributionManifestPath = "manifests/distributions/$Profile.json"
}

$manifest = Read-JsonFile -Path $DistributionManifestPath
$envConfig = Get-OptionalProperty -Object $manifest -Name "env"
if ($null -eq $envConfig) {
  throw "distribution has no env section: $DistributionManifestPath"
}

$centralTemplatePath = Resolve-RepoPath ([string]$envConfig.central_template_path)
if ([string]::IsNullOrWhiteSpace($CentralEnvPath)) {
  $CentralEnvPath = [string]$envConfig.central_env_path
}
$resolvedCentralEnvPath = Resolve-RepoPath $CentralEnvPath

if (-not (Test-Path -LiteralPath $resolvedCentralEnvPath -PathType Leaf)) {
  if ($NoCreateCentralEnv) {
    Write-Warning "central env missing: $resolvedCentralEnvPath"
  }
  else {
    Copy-IfMissing -Source $centralTemplatePath -Target $resolvedCentralEnvPath -Label "central env"
  }
}
else {
  Write-Host "exists: $resolvedCentralEnvPath"
}

$valueSourcePath = if (Test-Path -LiteralPath $resolvedCentralEnvPath -PathType Leaf) {
  $resolvedCentralEnvPath
}
else {
  $centralTemplatePath
}
$centralValues = Read-DotEnvMap -Path $valueSourcePath

foreach ($copyTarget in @(Get-OptionalProperty -Object $envConfig -Name "local_config_templates" -Default @())) {
  $source = Resolve-RepoPath ([string]$copyTarget.template_path)
  $target = Resolve-RepoPath ([string]$copyTarget.target_path)
  Copy-IfMissing -Source $source -Target $target -Label ([string]$copyTarget.id)
}

foreach ($target in @($envConfig.targets)) {
  $templatePath = Resolve-RepoPath ([string]$target.template_path)
  $targetPath = Resolve-RepoPath ([string]$target.target_path)
  if (-not (Test-Path -LiteralPath $templatePath -PathType Leaf)) {
    if ($DryRun) {
      Write-Warning "env template not present yet for $($target.id): $templatePath"
      Write-Host "New-Item -ItemType Directory -Force -Path $(Split-Path -Parent $targetPath)"
      Write-Host "Render env $($target.id): $templatePath -> $targetPath"
      continue
    }
    throw "env template missing for $($target.id): $templatePath"
  }
  if ((Test-Path -LiteralPath $targetPath) -and -not $Force) {
    Write-Host "exists: $targetPath"
    continue
  }

  $parent = Split-Path -Parent $targetPath
  $rendered = Convert-DotEnvTemplate -TemplatePath $templatePath -Values $centralValues -CentralPath $CentralEnvPath
  if ($DryRun) {
    Write-Host "New-Item -ItemType Directory -Force -Path $parent"
    Write-Host "Render env $($target.id): $templatePath -> $targetPath"
    continue
  }
  New-Item -ItemType Directory -Force -Path $parent | Out-Null
  Set-Content -LiteralPath $targetPath -Value $rendered -Encoding utf8
  Write-Host "rendered: $targetPath"
}
